### ISSUE TITLE
Incorrect Animation of Parent Groups While Using Blockbench Keywords.

### ISSUE THREAD

**Issue by TimelordRyan** [TheOneTrueZandra/Figura#57]
A Parent Group that uses a Blockbench keyword inside Root Group that uses the same keyword doesn't mimic the rotation of the Root Group. This issue also occurs if a Cube is listed after a Parent Group inside a Root Group.

Tested in the latest pre-release of Figura (0.0.4h)
https://youtu.be/1FfGJUdcqFE
https://imgur.com/a/oxX03nq

**Comment by TheOneTrueZandra** [comment]
This is not a bug.

Now that MIMIC and PARENT keywords aren't required to be roots, they can be double-applied. Your `MIMIC_HEAD` group is rotating, then the `HEAD` group is rotating again, or vice-versa.

Please rename one group, or the other, so that they no longer match a keyword, and the rotation is only applied to the highest group.
