### ISSUE TITLE
[ Enhancement ] Coloured Mark

### ISSUE THREAD

**Issue by SUPERN00Bthefirst** [TheOneTrueZandra/Figura#70]
I'm to lazy to create a PR for this
but we can have the icon colours still be cyan if we append §3 to them.
Example:
```
"figura.mark": "§3△"
```

**Comment by TheOneTrueZandra** [comment]
Have you actually tested if this works? We've got the style (the actual code) setting the color of the mark, and it still doesn't come up with the color.

**Comment by SUPERN00Bthefirst** [comment]
This would go in the lang file.
I have tested it, see attached image
![image](https://user-images.githubusercontent.com/49575478/115620649-6f9fd400-a2c3-11eb-85d6-19dc1604e039.png)

**Comment by Francy-chan** [comment]
The only issue with this is that it will always override the default text color, which is not a good idea

**Comment by SUPERN00Bthefirst** [comment]
We could always add §r to the end and have it reset back to default

**Comment by Hibiii** [comment]
`§3△§r` is a pretty hacky solution in my opinion, because Mojang's moving away from §. I did a quick test and `"figura.mark": {"text":"△", "color":"dark_aqua"}` doesn't work, translations are only strings. Anywhere that requires the mark or a star would need to be `.formatted(Formatting.AQUA)`. I may pick up on this suggestion.

**Comment by TheOneTrueZandra** [comment]
This is being resolved in PR 71 (/the equivalent)
