### ISSUE TITLE
UV Functions not Working as Expected

### ISSUE THREAD

**Issue by ENinja33** [TheOneTrueZandra/Figura#82]
From what I've heard, UV values in the getUV() and setUV() functions are intended to be normalized between 0 and 1. However, when I run part.getUV(), I get values greater than 1. Even more strangely, calling the function on two different parts (which each have the same UV coordinates in Blockbench) will give different numbers than one another.

Model with the problem:
[uv_bug.zip](https://github.com/TheOneTrueZandra/Figura/files/6401539/uv_bug.zip)

**Comment by P03W** [comment]
I made an image showing the weirdness i've had with UV, the texture is 128x128 but as you can see requires weird offsets to center the faces properly, red face is likely due to me not putting it on a power of 2, but still has weird scaling

![image](https://user-images.githubusercontent.com/52360088/116639791-daeb4500-a958-11eb-9ed2-3b5b762c680d.png)
Model i've been working on: [Robot.zip](https://github.com/TheOneTrueZandra/Figura/files/6402648/Robot.zip)
